# Generated by Django 3.0 on 2024-04-21 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('minimum_age', models.IntegerField(verbose_name='Edad Minima')),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': 'Sintomas',
            },
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=256, verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='medicines', verbose_name='Imagen')),
                ('release_date', models.DateField(verbose_name='Fecha de publicacion')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.Symptoms', verbose_name='Sintoma')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
    ]
