# Generated by Django 3.0 on 2024-04-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicines',
            options={'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
    ]
