# Generated by Django 3.0 on 2024-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20240420_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='description',
            field=models.CharField(default='Generic', max_length=256, verbose_name='Descripcion del sintoma'),
            preserve_default=False,
        ),
    ]
