# Generated by Django 3.0 on 2024-04-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_symptoms_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='symptom',
            field=models.ManyToManyField(blank=True, to='medicines.Symptoms', verbose_name='Sintoma'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='description',
            field=models.CharField(blank=True, max_length=256, verbose_name='Descripcion del sintoma'),
        ),
    ]
